name: lazer_events
description: "Aplicaci칩n de gesti칩n de eventos"
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2

  # State Management
  provider: ^6.1.2

  # UI
  cupertino_icons: ^1.0.8

  # Utilidades
  intl: ^0.19.0
  image_picker: ^1.1.3

  # Para manejo de im치genes de red
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Agrega estos assets para im치genes por defecto
  # assets:
  #  - assets/images/

  #fonts:
  #  - family: Roboto
  #   fonts:
  #    - asset: assets/fonts/Roboto-Regular.ttf
  #   - asset: assets/fonts/Roboto-Bold.ttf
  #    weight: 700
